### ISSUE TITLE
How to disable this feature in OpenShift

### ISSUE THREAD

**Issue by barryzhounb** [Maistra/ior#14]
I am using Istio 1.6.x on OpenShift 4.4, I want to disable this feature, is it possible? If yes, how to disable it.

**Comment by brian-avery** [comment]
Are you using Maistra, OpenShift Service Mesh, or Istio? Istio doesn't have support for IOR and you must define your routes manually.

**Comment by barryzhounb** [comment]
I am using OpenShift Service Mesh.

**Comment by dgn** [comment]
If you're using a v1 ServiceMeshControlPlane resource you can set `spec.istio.gateways.istio-ingressgateway.ior_enabled` to `false`. In a v2 SMCP, you have to set `spec.gateways.openshiftRoute.enabled` to `false` to disable the feature.

Closing this as we don't use GitHub issues
